const scs_input_device_input_t inputs[] = {
	//{"steering", "ToraCon Helper Steering", SCS_VALUE_TYPE_float},
	//{"aforward", "ToraCon Helper Forward", SCS_VALUE_TYPE_float},
	//{"abackward", "ToraCon Helper Backward", SCS_VALUE_TYPE_float},
	//{"clutch", "ToraCon Helper Clutch", SCS_VALUE_TYPE_float},
	//{"pause", "ToraCon Helper Pause", SCS_VALUE_TYPE_bool},
	{"parkingbrake", "ToraCon Helper Parking Brake", SCS_VALUE_TYPE_bool},
	//{"wipers", "ToraCon Helper Wipers", SCS_VALUE_TYPE_bool},
	//{"cruiectrl", "ToraCon Helper Cruise Control", SCS_VALUE_TYPE_bool},
	//{"cruiectrlinc", "ToraCon Helper Cruise Control Increase", SCS_VALUE_TYPE_bool},
	//{"cruiectrldec", "ToraCon Helper Cruise Control Decrease", SCS_VALUE_TYPE_bool},
	//{"cruiectrlres", "ToraCon Helper Cruise Control Reset", SCS_VALUE_TYPE_bool},
	//{"light", "ToraCon Helper Lights", SCS_VALUE_TYPE_bool},
	//{"hblight", "ToraCon Helper High Beams", SCS_VALUE_TYPE_bool},
	{"lblinker", "ToraCon Helper Left Blinker", SCS_VALUE_TYPE_bool},
	{"lblinkerh", "ToraCon Helper Left Blinkerh", SCS_VALUE_TYPE_bool},
	{"rblinker", "ToraCon Helper Right Blinker", SCS_VALUE_TYPE_bool},
	{"rblinkerh", "ToraCon Helper Right Blinkerh", SCS_VALUE_TYPE_bool},
	//{"quickpark", "ToraCon Helper Quickpark", SCS_VALUE_TYPE_bool},
	//{"drive", "ToraCon Helper Drive", SCS_VALUE_TYPE_bool},
	//{"reverse", "ToraCon Helper Reverse", SCS_VALUE_TYPE_bool},
	//{"cycl_zoom", "ToraCon Helper Cycle Zoom", SCS_VALUE_TYPE_bool},
	//{"tripreset", "ToraCon Helper Reset Trip", SCS_VALUE_TYPE_bool},
	//{"wipersback", "ToraCon Helper Rear Wipers", SCS_VALUE_TYPE_bool},
	//{"wipers0", "ToraCon Helper Wiper LVL 0", SCS_VALUE_TYPE_bool},
	//{"wipers1", "ToraCon Helper Wiper LVL 1", SCS_VALUE_TYPE_bool},
	//{"wipers2", "ToraCon Helper Wiper LVL 2", SCS_VALUE_TYPE_bool},
	//{"wipers3", "ToraCon Helper Wiper LVL 3", SCS_VALUE_TYPE_bool},
	//{"wipers4", "ToraCon Helper Wiper LVL 4", SCS_VALUE_TYPE_bool},
	//{"horn", "ToraCon Helper Horn", SCS_VALUE_TYPE_bool},
	//{"airhorn", "ToraCon Helper Airhorn", SCS_VALUE_TYPE_bool},
	//{"lighthorn", "ToraCon Helper Light Horn", SCS_VALUE_TYPE_bool},
	//{"cam1", "ToraCon Helper Camera 1", SCS_VALUE_TYPE_bool},
	//{"cam2", "ToraCon Helper Camera 2", SCS_VALUE_TYPE_bool},
	//{"cam3", "ToraCon Helper Camera 3", SCS_VALUE_TYPE_bool},
	//{"cam4", "ToraCon Helper Camera 4", SCS_VALUE_TYPE_bool},
	//{"cam5", "ToraCon Helper Camera 5", SCS_VALUE_TYPE_bool},
	//{"cam6", "ToraCon Helper Camera 6", SCS_VALUE_TYPE_bool},
	//{"cam7", "ToraCon Helper Camera 7", SCS_VALUE_TYPE_bool},
	//{"cam8", "ToraCon Helper Camera 8", SCS_VALUE_TYPE_bool},
	//{"mapzoom_in", "ToraCon Helper Zoom Map In", SCS_VALUE_TYPE_bool},
	//{"mapzoom_out", "ToraCon Helper Zoom Map Out", SCS_VALUE_TYPE_bool},
	//{"accmode", "ToraCon Helper ACC Mode", SCS_VALUE_TYPE_bool},
	//{"showmirrors", "ToraCon Helper Show Mirrors", SCS_VALUE_TYPE_bool},
	//{"flasher4way", "ToraCon Helper Hazard Lights", SCS_VALUE_TYPE_bool},
	//{"activate", "ToraCon Helper Activate", SCS_VALUE_TYPE_bool},
	//{"assistact1", "ToraCon Helper Assist Act 1", SCS_VALUE_TYPE_bool},
	//{"assistact2", "ToraCon Helper Assist Act 2", SCS_VALUE_TYPE_bool},
	//{"assistact3", "ToraCon Helper Assist Act 3", SCS_VALUE_TYPE_bool},
	//{"assistact4", "ToraCon Helper Assist Act 4", SCS_VALUE_TYPE_bool},
	//{"assistact5", "ToraCon Helper Assist Act 5", SCS_VALUE_TYPE_bool},
	{"retarderup", "ToraCon Helper Retarder Up", SCS_VALUE_TYPE_bool},
	{"retarderdown", "ToraCon Helper Retarder Down", SCS_VALUE_TYPE_bool},
	{"retarder0", "ToraCon Helper Retarder 0", SCS_VALUE_TYPE_bool},
	//{"retarder1", "ToraCon Helper Retarder 1", SCS_VALUE_TYPE_bool},
	//{"retarder2", "ToraCon Helper Retarder 2", SCS_VALUE_TYPE_bool},
	//{"retarder3", "ToraCon Helper Retarder 3", SCS_VALUE_TYPE_bool},
	//{"retarder4", "ToraCon Helper Retarder 4", SCS_VALUE_TYPE_bool},
	//{"retarder5", "ToraCon Helper Retarder 5", SCS_VALUE_TYPE_bool},
};
