const scs_input_device_input_t inputs[] = {
	//{"steering", "TCH Steering", SCS_VALUE_TYPE_float},
	//{"aforward", "TCH Forward", SCS_VALUE_TYPE_float},
	//{"abackward", "TCH Backward", SCS_VALUE_TYPE_float},
	//{"clutch", "TCH Clutch", SCS_VALUE_TYPE_float},
	//{"pause", "TCH Pause", SCS_VALUE_TYPE_bool},
	{"parkingbrake", "TCH Parking Brake", SCS_VALUE_TYPE_bool},
	//{"wipers", "TCH Wipers", SCS_VALUE_TYPE_bool},
	//{"cruiectrl", "TCH Cruise Control", SCS_VALUE_TYPE_bool},
	//{"cruiectrlinc", "TCH Cruise Control Increase", SCS_VALUE_TYPE_bool},
	//{"cruiectrldec", "TCH Cruise Control Decrease", SCS_VALUE_TYPE_bool},
	//{"cruiectrlres", "TCH Cruise Control Reset", SCS_VALUE_TYPE_bool},
	//{"light", "TCH Lights", SCS_VALUE_TYPE_bool},
	//{"hblight", "TCH High Beams", SCS_VALUE_TYPE_bool},
	{"lblinker", "TCH Left Blinker", SCS_VALUE_TYPE_bool},
	{"lblinkerh", "TCH Left Blinkerh", SCS_VALUE_TYPE_bool},
	{"rblinker", "TCH Right Blinker", SCS_VALUE_TYPE_bool},
	{"rblinkerh", "TCH Right Blinkerh", SCS_VALUE_TYPE_bool},
	//{"quickpark", "TCH Quickpark", SCS_VALUE_TYPE_bool},
	//{"drive", "TCH Drive", SCS_VALUE_TYPE_bool},
	//{"reverse", "TCH Reverse", SCS_VALUE_TYPE_bool},
	//{"cycl_zoom", "TCH Cycle Zoom", SCS_VALUE_TYPE_bool},
	//{"tripreset", "TCH Reset Trip", SCS_VALUE_TYPE_bool},
	//{"wipersback", "TCH Rear Wipers", SCS_VALUE_TYPE_bool},
	//{"wipers0", "TCH Wiper LVL 0", SCS_VALUE_TYPE_bool},
	//{"wipers1", "TCH Wiper LVL 1", SCS_VALUE_TYPE_bool},
	//{"wipers2", "TCH Wiper LVL 2", SCS_VALUE_TYPE_bool},
	//{"wipers3", "TCH Wiper LVL 3", SCS_VALUE_TYPE_bool},
	//{"wipers4", "TCH Wiper LVL 4", SCS_VALUE_TYPE_bool},
	//{"horn", "TCH Horn", SCS_VALUE_TYPE_bool},
	//{"airhorn", "TCH Airhorn", SCS_VALUE_TYPE_bool},
	//{"lighthorn", "TCH Light Horn", SCS_VALUE_TYPE_bool},
	//{"cam1", "TCH Camera 1", SCS_VALUE_TYPE_bool},
	//{"cam2", "TCH Camera 2", SCS_VALUE_TYPE_bool},
	//{"cam3", "TCH Camera 3", SCS_VALUE_TYPE_bool},
	//{"cam4", "TCH Camera 4", SCS_VALUE_TYPE_bool},
	//{"cam5", "TCH Camera 5", SCS_VALUE_TYPE_bool},
	//{"cam6", "TCH Camera 6", SCS_VALUE_TYPE_bool},
	//{"cam7", "TCH Camera 7", SCS_VALUE_TYPE_bool},
	//{"cam8", "TCH Camera 8", SCS_VALUE_TYPE_bool},
	//{"mapzoom_in", "TCH Zoom Map In", SCS_VALUE_TYPE_bool},
	//{"mapzoom_out", "TCH Zoom Map Out", SCS_VALUE_TYPE_bool},
	//{"accmode", "TCH ACC Mode", SCS_VALUE_TYPE_bool},
	//{"showmirrors", "TCH Show Mirrors", SCS_VALUE_TYPE_bool},
	//{"flasher4way", "TCH Hazard Lights", SCS_VALUE_TYPE_bool},
	{"activate", "TCH Activate", SCS_VALUE_TYPE_bool},
	//{"assistact1", "TCH Assist Act 1", SCS_VALUE_TYPE_bool},
	//{"assistact2", "TCH Assist Act 2", SCS_VALUE_TYPE_bool},
	//{"assistact3", "TCH Assist Act 3", SCS_VALUE_TYPE_bool},
	//{"assistact4", "TCH Assist Act 4", SCS_VALUE_TYPE_bool},
	//{"assistact5", "TCH Assist Act 5", SCS_VALUE_TYPE_bool},
	{"retarderup", "TCH Retarder Up", SCS_VALUE_TYPE_bool},
	{"retarderdown", "TCH Retarder Down", SCS_VALUE_TYPE_bool},
	{"retarder0", "TCH Retarder 0", SCS_VALUE_TYPE_bool},
	{"retarder1", "TCH Retarder 1", SCS_VALUE_TYPE_bool},
	{"retarder2", "TCH Retarder 2", SCS_VALUE_TYPE_bool},
	{"retarder3", "TCH Retarder 3", SCS_VALUE_TYPE_bool},
	{"retarder4", "TCH Retarder 4", SCS_VALUE_TYPE_bool},
	{"retarder5", "TCH Retarder 5", SCS_VALUE_TYPE_bool},
	{"engbraketog", "TCH EngineBrake Toggle", SCS_VALUE_TYPE_bool},
	{"engbrakeup", "TCH EngineBrake Up", SCS_VALUE_TYPE_bool},
	{"engbrakedwn", "TCH EngineBrake Down", SCS_VALUE_TYPE_bool},
};
