name: Assign self on issue and PR creation

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  assign-self:
    runs-on: ubuntu-latest
    steps:
      - name: Assign self to issue
        if: github.event_name == 'issues'
        run: |
          gh issue edit ${{ github.event.issue.number }} --assignee @me
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Assign self to pull request
        if: github.event_name == 'pull_request'
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-assignee @me --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

