name: Assign Author
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  assign-author:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/assign-author@v1
